import type { Metadata } from "next";
import Topbar from "@/app/components/Topbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <Topbar />
        {children}
      </body>
    </html>
  );
}
